name: Parameterized CI Build

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: "Test mode: 1=Frontend, 2=Backend, 3=Combined"
        required: true
        default: "3"
        type: choice
        options:
          - "1"
          - "2"
          - "3"

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_ROOT_USER: root
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
            echo "Error: DB_PASSWORD secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DB_NAME }}" ]; then      
            echo "Error: DB_NAME secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DB_ROOT_PASSWORD }}" ]; then
            echo "Error: DB_ROOT_PASSWORD secret is not set"
            exit 1
          fi
          echo "All required secrets are present"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install MySQL client for health checks
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        env:
          MYSQL_PWD: ${{ secrets.DB_ROOT_PASSWORD }}
        run: |
          # Wait for MySQL to be ready using environment variable for password
          for i in {1..30}; do
            if mysqladmin ping --host=127.0.0.1 --user=root --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL... (attempt $i/30)"
            sleep 2
          done

      - name: Initialize database
        run: |
          if [ ! -f setup_test_db.py ]; then
            echo "Error: setup_test_db.py not found"
            exit 1
          fi
          python setup_test_db.py

      - name: Start Applications
        env:
          HOST: 127.0.0.1
        run: |
          if [ "${{ inputs.test_mode }}" == "2" ] || [ "${{ inputs.test_mode }}" == "3" ]; then
            echo "Starting REST API server..."
            nohup python rest_app.py > server.log 2>&1 &

            # Wait for health check
            for i in {1..30}; do
              if curl -f http://127.0.0.1:5000/healthz > /dev/null 2>&1; then
                echo "REST API is healthy!"
                break
              fi
              echo "Waiting for REST API... (attempt $i/30)"
              sleep 2
            done
            if ! curl -f http://127.0.0.1:5000/healthz > /dev/null 2>&1; then
              echo "REST API failed to start after 60 seconds"
              exit 1
            fi
          fi

          if [ "${{ inputs.test_mode }}" == "1" ] || [ "${{ inputs.test_mode }}" == "3" ]; then
            echo "Starting Web App server..."
            nohup python web_app.py > web.log 2>&1 &

            # Wait for health check
            for i in {1..30}; do
              if curl -f http://127.0.0.1:5001/healthz > /dev/null 2>&1; then
                echo "Web App is healthy!"
                break
              fi
              echo "Waiting for Web App... (attempt $i/30)"
              sleep 2
            done
            if ! curl -f http://127.0.0.1:5001/healthz > /dev/null 2>&1; then
              echo "Web App failed to start after 60 seconds"
              exit 1
            fi
          fi

      - name: Run Frontend Tests
        if: ${{ inputs.test_mode == '1' }}
        run: python frontend_testing.py

      - name: Run Backend Tests
        if: ${{ inputs.test_mode == '2' }}
        run: python backend_testing.py

      - name: Run Combined Tests
        if: ${{ inputs.test_mode == '3' }}
        run: python combined_testing.py

      - name: Cleanup Environment
        if: always()
        run: |
          if [ -f clean_environment.py ]; then
            python clean_environment.py
          else
            echo "Warning: clean_environment.py not found, skipping cleanup"
          fi

      - name: Show Logs on Failure
        if: failure()
        run: |
          echo "=== REST API Logs ==="
          cat server.log 2>/dev/null || echo "No server log found"
          echo ""
          echo "=== Web App Logs ==="
          cat web.log 2>/dev/null || echo "No web log found"
